---
title: '**Christopher J. Fiscus**'
geometry: margin=0.5in
header-includes: \usepackage{hyperref}
output:
  pdf_document:
    includes:
      in_header: header.tex
  github_document: default
  word_document: default
li {list-style-type: none;}
fontsize: 11pt
---
\begin{center}
Graduate Student Researcher\\
Department of Botany and Plant Sciences, University of California, Riverside\\
\href{mailto:cfisc004@ucr.edu}{cfisc004@ucr.edu} • \href{https://linkedin.com/in/cjfiscus}{LinkedIn} • \href{https://github.com/cjfiscus}{GitHub}• \href{https://twitter.com/cjfiscu}{@cjfiscu}
\end{center}

#### EDUCATION
**Ph.D. Genetics, Genomics and Bioinformatics**  
University of California, Riverside, expected 2021

**B.S. Biotechnology**  
University of California, Davis, June 2015

#### RESEARCH EXPERIENCE
**Graduate Student Researcher**, University of California, Riverside, 9/2016-present  
Investigating genetics, genomics and evolution of the Poaceae and Brassicaceae.   
PI: Dr. Daniel Koenig, Department of Botany & Plant Sciences  

**Undergraduate Researcher**, University of California, Davis, 1/2014- 10/2014  
Investigated evidence of centromere drive from next-generation sequence data in maize.  
PI: Dr. Jeffrey Ross-Ibarra, Department of Plant Sciences  

**Undergraduate Intern**, University of California, Davis, 4/2012- 6/2012  
Investigated genetic and environmental interactions affecting seed dormancy in lettuce.  
PI: Dr. Kent J. Bradford, Department of Plant Sciences  

#### EMPLOYMENT

**Quality Control Laboratory Technician**, Charles Krug Winery, 12/2015- 8/2016  
Performed laboratory analyses of finished wine to ensure that legal and product quality specifications are met.  

**Harvest Laboratory Technician**, Charles Krug Winery (via Apex Life Sciences), 8/2015- 11/2015  
Supported winemaking operations by performing quantitative physical, chemical, and microbiological analyses of berries, musts, and wines.  

**Tutor**, One-on-One Tutoring and Educational Mapping, 9/2014- 6/2015  
Assisted students in grades 9-12 with academic coursework in science and mathematics.  

**Student Assistant**, Ross-Ibarra Laboratory, University of California, Davis, 10/2012- 9/2013  
Assisted with laboratory and greenhouse experiments in support of faculty-sponsored research projects.

\


#### TEACHING EXPERIENCE 
**Teaching Assistant**, University of California, Riverside, 1/2018- 3/2018  
BIOL 102: Introductory Genetics  

**Community Education Instructor**, Modesto Junior College, 6/2013, 6/2014   
Science Camp  

**Community Education Assistant Instructor**, Modesto Junior College, 2012-2014  
Introductury LEGO Mindstorms NXT Robotics, 6-7/2012, 6-7/2013, 6-7/2014   
Advanced LEGO Mindstorms NXT Robotics, 6/2013, 7/2014  
Video Game Programming for Kids, 7/2014  

#### CONTRIBUTED PRESENTATIONS (+ denotes presenter)
Landis JB+, Guercio AM, Fiscus CJ, Koenig D. Phenotypic variation and genetic control of long-term success in a near century long study of barley (Hordeum vulgare). Botany Conference 2018  

Landis JB+, Fiscus CJ, Guercio AM, Koenig D. Elucidating the genetic control of long-term success in a near century long study of barley (Hordeum vulgare). Evolution Conference 2017

#### AWARDS AND FELLOWSHIPS
Dean's Distinguished Fellowship (UCR), 2016-2021  
California Highway Patrol 11-99 Foundation Scholarship, 2011-2015

#### PROFESSIONAL AFFILIATIONS
Society for Molecular Biology and Evolution, 2017-present  
Botanical Society of America, 2017-present

#### OUTREACH
National History Day Judge, Riverside Unified School District, 1/2018  
Master Plant Science Team, PlantingScience, 2017-2018    
Guest Speaker, James C. Enochs High School Forensics/Biotechnology Career Pathway Program, 3/2017  
Design/ Core Values Judge, FIRST LEGO League, 2010-2014  

#### MENTORING
Chris Roland Valdez, NSF-CEPCEB REU Program in Next Generation Plant Biology, 6-8/2018  
Selena Burke, NSF-CEPCEB REU Program in Next Generation Plant Biology, 6-8/2017  

#### SERVICE
Secretary, GGB Graduate Student Association (UCR), 2017-2018
