---
geometry: margin=0.5in
header-includes: 
- \usepackage{hyperref}
- \usepackage{multicol}
- \usepackage{helvet}
- \usepackage[T1]{fontenc}
- \usepackage{orcidlink}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \setlength{\headheight}{0pt}
- \renewcommand\familydefault{\sfdefault} 
- \geometry{footskip=0.5cm}
- \usepackage{titlesec}
-  \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
-  \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
-  \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \fancyhead{}
- \fancyhead[R]{resume for Christopher J. Fiscus, PhD}
- \usepackage{enumitem}
- \setlist[itemize]{topsep=0pt, leftmargin=16pt}

output:
  pdf_document:
    includes:
      in_header: header.tex
  github_document: default
  word_document: default
li {list-style-type: none;}
fontsize: 11pt
---
\thispagestyle{plain}
\begin{multicols}{2}
\begin{flushleft}
{\LARGE \textbf{Christopher J. Fiscus, PhD}\par}
\vfill
\textbf{Bioinformatics Scientist} \\   
San Diego, California
\end{flushleft}

\columnbreak

\begin{flushright}
\begin{tabular}{rp{0.30\linewidth}}
\faPhone & \href{tel:+12096139384}{1-209-613-9384} \\
\faEnvelopeO & \href{mailto:fiscuscj@gmail.com}{fiscuscj@gmail.com} \\
\faLinkedin & \href{https://www.linkedin.com/in/fiscuscj}{fiscuscj} \\
\faGithub & \href{https://github.com/cjfiscus}{cjfiscus} 
\end{tabular}
\end{flushright}

\end{multicols}


## Summary
R&D Scientist with extensive experience in bioinformatics, computational biology, and data science. Strong track record of leading high-impact research projects within cross-functional teams. Expert communicator with a talent for translating complex technical information to diverse stakeholders, fostering collaboration and driving project success. 

## Professional Experience
**Bioinformatics Scientist I** \hfill 10/2024 - Present  
Exact Sciences Corp. \hfill San Diego, CA

**Postdoctoral Researcher** \hfill 09/2022 - 09/2024  
University of California, Irvine \hfill Irvine, CA  

* Conducted cutting-edge research on wild grape genomics utilizing novel genomics and machine learning algorithms, leading to 4 conference presentations (3 talks, 1 poster) 

* Led a team of 4 in the 2023 Pan-Structural Variation Hackathon in the Cloud, designed an algorithm to characterize copy number variation from next generation sequencing data 

* Developed and implemented bioinformatics algorithms for analysis of multi-omics NGS sequencing data in a high-performance computing environment


**Graduate Student Researcher** \hfill 09/2016 - 09/2022  
University of California, Riverside \hfill Riverside, CA  

* Contributed to genomics research projects as part of a cross-functional R&D team, leading to 3 peer-reviewed publications and 8 conference presentations (2 talks, 6 posters)  

* Developed a novel pipeline utilizing K-mer frequencies from WGS reads to profile genomes, estimate repeat copy number variation, and map genetic basis of CNV using GWAS  

* Mentored and managed teams of 1-2 direct reports (5 mentees total), enhancing their technical skills and contributing to successful project outcomes 


**Quality Control Laboratory Technician** \hfill 12/2015 - 08/2016  
Charles Krug Winery \hfill St. Helena, CA  

* Conducted enology laboratory tests throughout production, ensuring legal compliance and maintaining quality standards across multiple product lines  

* Redesigned 5 SOPs for quality control laboratory assays, improving laboratory efficiency by 20% and ensuring consistent, reliable testing procedures  

* Collaborated with production teams to identify and resolve product quality issues, enhancing overall product consistency through thorough data analysis and problem-solving   


**Harvest Laboratory Technician** \hfill 08/2015 - 12/2015  
Charles Krug Winery (via Apex Life Sciences) \hfill St. Helena, CA

* Conducted enology laboratory tests and data evaluation supporting the production of 1.5 million cases annually  

## Skills
* **Data analysis**: inferential statistics, regression, clustering, PCA, machine learning (random forests) 

* **Programming**: R (tidyverse, ggplot2), bash, python 

* **Bioinformatics**: NGS data analysis, SNP calling, GWAS, bwa, GATK, samtools/bcftools, bedtools, plink   

* **Computing**: Unix command line, SLURM (HPC), conda, git (version control), snakemake (workflow) 

## Education   
**Ph.D. Genetics, Genomics and Bioinformatics** \hfill 2022  
University of California, Riverside

**B.S. Biotechnology** \hfill 2015  
University of California, Davis

## Certifications
**AWS Cloud Technical Essentials** \hfill 11/2023  
Coursera 

## Publications \orcidlink{https://orcid.org/0000-0001-9569-1809} `0000-0001-9569-1809`
<!-- use PLoS Genetics citation style but add all authors -->
Martin GT, **Fiscus CJ**, Gaut BS. Quantifying evolution of SNPs that affect RNA secondary structure in *Arabidopsis thaliana* genes. bioRxiv. 2024. p. 2024.09.27.615253. doi:10.1101/2024.09.27.615253   

**Fiscus CJ**, Aguirre-Liguori JA, Gaut GRJ, Gaut BS. Climate, population size, and dispersal influences mutational load across the landscape in *Vitis arizonica*. bioRxiv. 2024. p. 2024.08.22.609253. doi:10.1101/2024.08.22.609253  

Landis JB, Guercio AM, Brown KE, **Fiscus CJ**, Morrell PL, Koenig D. Natural selection drives emergent genetic homogeneity in a century-scale experiment with barley. Science. 2024;385: eadl0038. doi:10.1126/science.adl0038  

Deb SK, Kalra D, Kubica J, Stricker E, Truong VQ, Zeng Q, **Fiscus CJ**, [41 authors], Sedlazeck FJ, Busby B. The fifth international hackathon for developing computational cloud-based tools and resources for pan-structural variation and genomics. F1000Res. 2024;13: 708. doi:10.12688/f1000research.148237.1  

**Fiscus CJ**, Herniter IA, Tchamba M, Paliwal R, Muñoz-Amatriaín M, Roberts PA, Abberton M, Alaba O, Close TJ, Oyatomi O, Koenig D. The pattern of genetic variability in a core collection of 2,021 cowpea accessions. G3. 2024. doi:10.1093/g3journal/jkae071 

Martinez SE, Conn CE, Guercio AM, Sepulveda C, **Fiscus CJ**, Koenig D, Shabek N, Nelson DC. A KARRIKIN INSENSITIVE2 paralog in lettuce mediates highly sensitive germination responses to karrikinolide. Plant Physiol. 2022. doi:10.1093/plphys/kiac328
