---
geometry: margin=0.5in
header-includes: 
- \usepackage{hyperref}
- \usepackage{multicol}
- \usepackage{helvet}
- \usepackage[T1]{fontenc}
- \usepackage{orcidlink}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \setlength{\headheight}{0pt}
- \fancyhead[R]{curriculum vitae for Christopher J. Fiscus, PhD}
- \renewcommand\familydefault{\sfdefault} 
- \geometry{footskip=0.5cm}
output:
  pdf_document:
    includes:
      in_header: header.tex
  github_document: default
  word_document: default
li {list-style-type: none;}
fontsize: 11pt
---
\thispagestyle{plain}
\begin{multicols}{2}
\begin{flushleft}
{\LARGE \textbf{Christopher J. Fiscus, PhD}\par}
Department of Ecology and Evolutionary Biology
University of California, Irvine
\end{flushleft}

\columnbreak

\begin{flushright}
\begin{tabular}{rp{0.30\linewidth}}
\faEnvelopeO & \href{mailto:cfiscus@uci.edu}{cfiscus@uci.edu} \\
\faTwitter & \href{https://twitter.com/fiscuscj}{@fiscuscj} \\
\faUser & \href{https://cjfiscus.github.io/}{cjfiscus.github.io} \\
\faGithub & \href{https://github.com/cjfiscus}{cjfiscus} \\
\faLinkedin & \href{www.linkedin.com/in/fiscuscj}{fiscuscj}
\end{tabular}
\end{flushright}

\end{multicols}

# Education   
**Ph.D. Genetics, Genomics and Bioinformatics**, University of California, Riverside \hfill 2022  
Dissertation: *Causes and consequences of plant genome evolution*  
Advisor: [Dr. Daniel Koenig](https://iigb.ucr.edu/koenig/)

**B.S. Biotechnology**, University of California, Davis \hfill 2015  

# Professional Experience
**Postdoctoral Scholar**, University of California, Irvine \hfill 09/2022 - Present  
Dept of Ecology and Evolutionary Biology  
Advisor: [Dr. Brandon Gaut](https://www.faculty.uci.edu/profile.cfm?faculty_id=4561)

**Graduate Student Researcher**, University of California, Riverside \hfill 09/2016 - 09/2022  
Dept of Botany and Plant Sciences   
Advisor: [Dr. Daniel Koenig](https://iigb.ucr.edu/koenig/)

**Quality Control Laboratory Technician**, Charles Krug Winery \hfill 12/2015 - 08/2016  

**Harvest Laboratory Technician**, Charles Krug Winery (via Apex Life Sciences) \hfill 08/2015 - 12/2015 

**Undergraduate Researcher**, University of California, Davis \hfill 01/2014 - 10/2014  
Advisor: [Dr. Jeffrey Ross-Ibarra](https://biology.ucdavis.edu/people/jeffrey-ross-ibarra)  

**Undergraduate Intern**, University of California, Davis \hfill 03/2012 - 06/2012  
Advisor: [Dr. Kent J. Bradford](https://www.plantsciences.ucdavis.edu/people/kent-bradford) 

# Teaching Experience
**Guest Lecturer**, University of California, Riverside  
BIOL 119. Introduction to Genomics and Bioinformatics. \hfill 02/2020   
Lecture: Genomics, Phenotype and Disease. 

**Teaching Assistant**, University of California, Riverside  
BIOL 119. Introduction to Genomics and Bioinformatics \hfill 01-03/2019, 01-03/2020, 01-03/2021   
BIOL 102. Introductory Genetics \hfill 01-03/2018 

**Community Education Instructor**, Modesto Junior College   
Science Camp \hfill 06-08/2013, 06-08/2014 

**Community Education Assistant Instructor**, Modesto Junior College  
Introductory LEGO Mindstorms NXT Robotics \hfill 06-08/2012, 06-08/2013, 06-08/2014   
Advanced LEGO Mindstorms NXT Robotics \hfill 06-08/2013, 06-08/2014  
Video Game Programming for Kids \hfill 06-08/2014  

# Publications \orcidlink{https://orcid.org/0000-0001-9569-1809} `0000-0001-9569-1809`   

## Preprints 
Landis JB, Guercio AM, Brown KE, **Fiscus CJ**, Morrell PL, Koenig D. Natural selection drives emergent genetic homogeneity in a century-scale experiment with barley. bioRxiv. 2023. p. 2023.09.22.557807. doi:10.1101/2023.09.22.557807  

## In press
<!-- use PLoS Genetics citation style but add all authors -->
Deb SK, Kalra D, Kubica J, Stricker E, Truong VQ, Zeng Q, **Fiscus CJ**, [41 authors], Sedlazeck FJ, Busby B. The fifth international hackathon for developing computational cloud-based tools and resources for pan-structural variation and genomics. F1000Res. 2024;13: 708. doi:10.12688/f1000research.148237.1  

**Fiscus CJ**, Herniter IA, Tchamba M, Paliwal R, Muñoz-Amatriaín M, Roberts PA, Abberton M, Alaba O, Close TJ, Oyatomi O, Koenig D. The pattern of genetic variability in a core collection of 2,021 cowpea accessions. G3. 2024. doi:10.1093/g3journal/jkae071 

Martinez SE, Conn CE, Guercio AM, Sepulveda C, **Fiscus CJ**, Koenig D, Shabek N, Nelson DC. A KARRIKIN INSENSITIVE2 paralog in lettuce mediates highly sensitive germination responses to karrikinolide. Plant Physiol. 2022. doi:10.1093/plphys/kiac328

<!-- ### NON-PEER REVIEWED PUBLICATIONS -->
<!-- **Fiscus CJ** (2015) [Data Reproducibility: The Chink in Science's Armor](https://aggietranscript.ucdavis.edu/data-reproducibility-the-chink-in-sciences-armor/) *The Aggie Transcript* --> 

# Selected Presentations
**Fiscus CJ**, Aguirre-Liguori JA, Gaut GRJ, Gaut BS. Landscape genomics and mutational load in *Vitis arizonica*. Talk. Southern California Evolutionary Genetics and Genomics Meeting (SCalE) 2024. Pasadena, CA, USA   

**Fiscus CJ**, Landis JB, Morales-Cruz A, Gaut BS. Disentangling the evolution of grape crop wild relatives. Talk. Plant and Animal Genome Conference 31. San Diego, CA, USA   

**Fiscus CJ**, Landis JB, Morales-Cruz A, Gaut BS. Disentangling the evolution of grape crop wild relatives. Talk. Southern California Plant Biology Symposium 2023. Riverside, CA, USA   

**Fiscus CJ**, Koenig D. The genetic control of rapid genome content divergence in *Arabidopsis thaliana*. Poster. SMBE 2023. Ferrara, Italy  

**Fiscus CJ**, Koenig D. The genetic control of rapid genome content divergence in *Arabidopsis thaliana*. Talk. SMBEeverywhere GS7. Online  

**Fiscus CJ**. Causes and consequences of plant genome evolution. Seminar. 01/2023.  Friends of Evolution Seminar Series, Dept. of Ecology and Evolutionary Biology UC Irvine. Irvine, CA, USA

<!-- Koenig D+, **Fiscus CJ**, Abberton M, Close TJ, Muñoz-Amatriaín M, Oyatomi O. A genetic framework to understand climate adaptation in cowpea. Oral. PAG30. San Diego, CA, USA --> 

<!-- Koenig D+, **Fiscus CJ**. Understanding variation in the rate of genomic change in *Arabidopsis thaliana*. Oral. PAG30 San Diego, CA, USA --> 

**Fiscus CJ**, Koenig D. The genetic control of rapid genome content divergence in *Arabidopsis thaliana*. Poster. PEQG2022. Pacific Grove, CA, USA  

**Fiscus CJ**, Koenig D. A catalog of genome content variation in *Arabidopsis thaliana*. Poster. TAGC 2020 Online. Online. doi: [10.6084/m9.figshare.12148632.v1](https://doi.org/10.6084/m9.figshare.12148632.v1)

<!-- Landis JB, Brown KE, Marzolino J, Guercio A, **Fiscus CJ**, Koenig D+. [The genomic basis of adaptation in a ninety year long barley experiment.](https://genetics-gsa.org/tagc-2020/wp-content/uploads/sites/4/2020/04/200421-TAGC20-Abstract-Book-v1a.pdf) Oral. TAGC 2020 Online. Online. --> 

<!-- Landis JB, **Fiscus CJ**, Guercio A, Koenig D+. [The genetic architecture of adaptation in the long term barley composite cross experiments.](https://plan.core-apps.com/pag_2020/abstract/6f7bedec-7049-40b5-a8c3-d18eb5a858eb). Talk. PAG XXVIII. San Diego, CA --> 

<!-- **Fiscus CJ**, Koenig D. A catalog of genome content variation in *Arabidopsis thaliana*. Talk. Annual Genetics, Genomics, and Bioinformatics Student Symposium 2019. Riverside, CA, USA --> 

**Fiscus CJ**, Koenig D. A K-mer based approach to characterize the dark matter of the *Arabidopsis thaliana* genome. Poster. Southern California Evolutionary Genetics and Genomics Meeting (SCalE) 2019. Irvine, CA, USA  

**Fiscus CJ**, Koenig D. [A K-mer based approach to characterize the dark matter of the *Arabidopsis thaliana* genome](http://smbe2019.org/media/1058/smbe-2019-abstract-book.pdf). Poster. SMBE 2019. Manchester, UK  

<!-- Landis JB+, Nguyen J, Villamor I, Guercio A, **Fiscus CJ**, Quigley M, Ophelders T, Eithun M, Munch E, Chitwood D, Koenig D. [Integrating next-generation high resolution phenotype acquisition with genotypes to study adaptation in barley (Hordeum vulgare)](https://2019.botanyconference.org/engine/search/365.html?func=detail&aid=365). Oral. Botany 2019. Tucson, AZ -->

<!-- Valdez CR, **Fiscus CJ**, Koenig D. Characterization of genome content variation in *Oryza sativa*. Poster. UCR Graduate Program in Genetics, Genomics and Bioinformatics Symposium 2019. Poster. Riverside, CA, USA --> 

<!-- Landis JB+, Guercio AM, **Fiscus CJ**, Koenig D. [Phenotypic variation and genetic control of long-term success in a near century long study of barley (Hordeum vulgare)](http://2018.botanyconference.org/engine/search/index.php?func=detail&aid=294). Oral. Botany 2018. Rochester, MN --> 

<!-- Landis JB+, **Fiscus CJ**, Guercio AM, Koenig D. [Elucidating the genetic control of long-term success in a near century long study of barley (Hordeum vulgare)](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/final_evol2017_program.pdf). Oral. Evolution 2017. Portland, OR --> 

# Awards and Fellowships
SMBE 2024 Young Investigator Award- $2000 \hfill 2024  
UCR Graduate Student Association Conference Travel Grant- $400 \hfill 2022  
Earle C. Anthony Graduate Student Travel Award (UCR)-$1000 \hfill 2020  
UCR Graduate Student Association Conference Travel Grant- $900 \hfill 2019  
Best Student Appetizer, UCR Botany and Plant Sciences Holiday Party \hfill 2017, 2018, 2019    
Dean's Distinguished Fellowship (UCR)- $210,938 \hfill 2016 - 2021    
<!-- California Highway Patrol 11-99 Foundation Scholarship \hfill 2011 - 2015 --> 

# Outreach
Scientist Mentor, [PlantingScience](https://www.plantingscience.org/) \hfill 09/2017 - 05/2020    
Volunteer, UC Riverside Plant Discovery Day \hfill 04/2019   
<!-- National History Day Judge, Riverside Unified School District \hfill January 2018 --> 
Master Plant Science Team, [PlantingScience](https://www.plantingscience.org/) \hfill 09/2017 - 05/2018    
Guest Speaker, James C. Enochs High School Forensics/Biotechnology Career Pathway Program \hfill 03/2017  
<!-- Design / Core Values Judge, FIRST LEGO League \hfill 2010 - 2014 --> 

# Service
Organizer, Southern California Evolutionary Genetics and Genomics Meeting (SCalE) \hfill 2023  
President, GGB Graduate Student Association (UCR) \hfill 2019 - 2020  
Secretary, GGB Graduate Student Association (UCR) \hfill 2017 - 2018

# Professional Affiliations
Genetics Society of America \hfill 2020 - Present   
Society for Molecular Biology and Evolution \hfill 2017 - Present   
<!-- Botanical Society of America \hfill 2017-2019  --> 

# Mentoring
Livia Nguyen, UCR undergraduate \hfill 2020   
Caitlin Santos, UCR undergraduate \hfill 2019 - 2021    
<!-- Kirsten Trimble, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill Summer 2019 -->
Johnny Nguyen-Tran, UCR undergraduate \hfill 2019      
Chris Roland Valdez, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill 06-08/2018  
Selena Burke, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill 06-08/2017  
