---
geometry: margin=0.5in
header-includes: \usepackage{hyperref}
output:
  pdf_document:
    includes:
      in_header: header.tex
  github_document: default
  word_document: default
li {list-style-type: none;}
fontsize: 11pt
---
\begin{center}
{\LARGE \textbf{Christopher J. Fiscus}\par}
\end{center}
\begin{center}
Department of Botany and Plant Sciences, University of California, Riverside\\
900 University Ave Riverside, CA 92521 \\
\faEnvelopeO \quad \href{mailto:cfisc004@ucr.edu}{cfisc004@ucr.edu} • \faTwitter \quad \href{https://twitter.com/fiscuscj}{@fiscuscj} • \faUser \quad \href{https://cjfiscus.github.io/}{website} • \faGithub \quad \href{https://github.com/cjfiscus}{GitHub} • \faLinkedin \quad \href{https://linkedin.com/in/cjfiscus}{LinkedIn}
\end{center}

### EDUCATION   
**Ph.D. Genetics, Genomics and Bioinformatics** \hfill expected 2021  
University of California, Riverside 

**B.S. Biotechnology**  \hfill June 2015  
University of California, Davis 

### PROFESSIONAL EXPERIENCE
**Graduate Student Researcher**, University of California, Riverside \hfill 2016-Present    
Advisor: [Dr. Daniel Koenig](https://iigb.ucr.edu/koenig/)

**Quality Control Laboratory Technician**, Charles Krug Winery \hfill 2015-2016  

**Harvest Laboratory Technician**, Charles Krug Winery (via Apex Life Sciences) \hfill 2015 

**Undergraduate Researcher**, University of California, Davis \hfill 2014  
Advisor: [Dr. Jeffrey Ross-Ibarra](https://biology.ucdavis.edu/people/jeffrey-ross-ibarra)  

**Undergraduate Intern**, University of California, Davis \hfill Spring 2012  
Advisor: [Dr. Kent J. Bradford](https://www.plantsciences.ucdavis.edu/people/kent-bradford) 

### TEACHING EXPERIENCE
**Guest Lecturer**, University of California, Riverside  
BIOL 119. Introduction to Genomics and Bioinformatics. \hfill Winter 2020   
Lecture: Genomics, Phenotype and Disease. 

**Teaching Assistant**, University of California, Riverside  
BIOL 119. Introduction to Genomics and Bioinformatics \hfill Winter 2019, 2020, 2021   
BIOL 102. Introductory Genetics \hfill Winter 2018 

**Community Education Instructor**, Modesto Junior College   
Science Camp \hfill Summer 2013-2014 

**Community Education Assistant Instructor**, Modesto Junior College  
Introductory LEGO Mindstorms NXT Robotics \hfill Summer 2012-2014   
Advanced LEGO Mindstorms NXT Robotics \hfill Summer 2013-2014  
Video Game Programming for Kids \hfill Summer 2014  

### NON-PEER REVIEWED PUBLICATIONS
**Fiscus CJ** (2015) [Data Reproducibility: The Chink in Science's Armor](https://aggietranscript.ucdavis.edu/data-reproducibility-the-chink-in-sciences-armor/) *The Aggie Transcript*  

### CONTRIBUTED PRESENTATIONS (+ denotes presenter)  
**Fiscus CJ+**, Koenig D. [A Catalog of Genome Content Variation in *Arabidopsis thaliana*.](https://genetics-gsa.org/tagc-2020/wp-content/uploads/sites/4/2020/04/200421-TAGC20-Abstract-Book-v1a.pdf) Poster. TAGC 2020 Online. Online. doi: [10.6084/m9.figshare.12148632.v1](https://doi.org/10.6084/m9.figshare.12148632.v1)

Landis JB, Brown KE, Marzolino J, Guercio A, **Fiscus CJ**, Koenig D+. [The Genomic Basis of Adaptation in a Ninety Year Long Barley Experiment.](https://genetics-gsa.org/tagc-2020/wp-content/uploads/sites/4/2020/04/200421-TAGC20-Abstract-Book-v1a.pdf) Oral. TAGC 2020 Online. Online.  

Landis JB, **Fiscus CJ**, Guercio A, Koenig D+. [The Genetic Architecture of Adaptation in the Long Term Barley Composite Cross Experiments.](https://plan.core-apps.com/pag_2020/abstract/6f7bedec-7049-40b5-a8c3-d18eb5a858eb). Talk. PAG XXVIII. San Diego, CA  

**Fiscus CJ+**, Koenig D. A Catalog of Genome Content Variation in *Arabidopsis thaliana*. Talk. Annual Genetics, Genomics, and Bioinformatics Student Symposium 2019. Riverside, CA  

**Fiscus CJ+**, Koenig D. A K-mer Based Approach to Characterize the Dark Matter of the *Arabidopsis thaliana* Genome. Poster. Southern California Evolutionary Genetics and Genomics Meeting 2019. Irvine, CA  

**Fiscus CJ+**, Koenig D. [A K-mer Based Approach to Characterize the Dark Matter of the *Arabidopsis thaliana* Genome](http://smbe2019.org/media/1058/smbe-2019-abstract-book.pdf). Poster. SMBE 2019. Manchester, UK  

Landis JB+, Nguyen J, Villamor I, Guercio A, **Fiscus CJ**, Quigley M, Ophelders T, Eithun M, Munch E, Chitwood D, Koenig D. [Integrating next-generation high resolution phenotype acquisition with genotypes to study adaptation in barley (Hordeum vulgare)](https://2019.botanyconference.org/engine/search/365.html?func=detail&aid=365). Oral. Botany 2019. Tucson, AZ

Valdez CR, **Fiscus CJ+**, Koenig D. Characterization of Genome Content Variation in *Oryza sativa*. Poster. UCR Graduate Program in Genetics, Genomics and Bioinformatics Symposium 2019. Poster. Riverside, CA  

Landis JB+, Guercio AM, **Fiscus CJ**, Koenig D. [Phenotypic variation and genetic control of long-term success in a near century long study of barley (Hordeum vulgare)](http://2018.botanyconference.org/engine/search/index.php?func=detail&aid=294). Oral. Botany 2018. Rochester, MN  

Landis JB+, **Fiscus CJ**, Guercio AM, Koenig D. [Elucidating the genetic control of long-term success in a near century long study of barley (Hordeum vulgare)](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/final_evol2017_program.pdf). Oral. Evolution 2017. Portland, OR  

### AWARDS AND FELLOWSHIPS
Earle C. Anthony Graduate Student Travel Award (UCR)-$1000 \hfill 2020  
UCR Graduate Student Association Conference Travel Grant- $900 \hfill 2019  
Best Student Appetizer, Botany and Plant Sciences Holiday Party \hfill 2017, 2018, 2019    
Dean's Distinguished Fellowship (UCR) \hfill 2016-2018   
<!-- California Highway Patrol 11-99 Foundation Scholarship \hfill 2011-2015 --> 

### PROFESSIONAL AFFILIATIONS
Genetics Society of America \hfill 2020-Present   
Society for Molecular Biology and Evolution \hfill 2017-Present   
<!-- Botanical Society of America \hfill 2017-2019  --> 

### OUTREACH
Scientist Mentor, [PlantingScience](https://www.plantingscience.org/) \hfill 2017-Present   
<!-- Mentor, James C. Enochs High School Eagles Soar Program \hfill 2019 --> 
Volunteer, UC Riverside Plant Discovery Day \hfill April 2019   
National History Day Judge, Riverside Unified School District \hfill January 2018   
Master Plant Science Team, [PlantingScience](https://www.plantingscience.org/) \hfill 2017-2018    
Guest Speaker, James C. Enochs High School Forensics/Biotechnology Career Pathway Program \hfill March 2017  
<!-- Design / Core Values Judge, FIRST LEGO League \hfill 2010-2014 --> 

### SERVICE
President, GGB Graduate Student Association (UCR) \hfill 2019-2020  
Secretary, GGB Graduate Student Association (UCR) \hfill 2017-2018

### MENTORING
Livia Nguyen, UCR undergraduate \hfill 2020   
Caitlin Santos, UCR undergraduate \hfill 2019-2020    
<!-- Kirsten Trimble, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill Summer 2019 -->
Johnny Nguyen-Tran, UCR undergraduate \hfill 2019      
Chris Roland Valdez, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill Summer 2018  
Selena Burke, NSF-CEPCEB REU Program in Next Generation Plant Biology \hfill Summer 2017  
